version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - ./src/main/resources/cassandra/schema.cql:/schema.cql
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 15s
      timeout: 5s
      retries: 10

  cassandra_init:
    image: cassandra:latest
    container_name: cassandra_init
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./src/main/resources/cassandra/schema.cql:/schema.cql
    command: >
      sh -c "
        until cqlsh -u cassandra -p cassandra cassandra; do
          sleep 3;
        done;
        echo 'Cassandra is up - executing CQL script';
        cqlsh -u cassandra -p cassandra cassandra -f /schema.cql;
        echo 'CQL script executed successfully';
      "